---
# Tasks for managing cutover process
- name: Stop source VM if running
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    state: stopped
  ignore_errors: yes

- name: Start migrated VM in Azure
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    state: started

- name: Update DNS records
  include_tasks: update_dns.yml

- name: Verify connectivity
  include_tasks: verify_connectivity.yml