---
- name: Configure Post-Migration Setup
  hosts: azure_vms
  become: true

  vars:
    backup_vault: "{{ lookup('env', 'AZURE_BACKUP_VAULT') }}"
    resource_group: "{{ lookup('env', 'AZURE_RESOURCE_GROUP') }}"
    subscription_id: "{{ lookup('env', 'ARM_SUBSCRIPTION_ID') }}"

  tasks:
    - name: Install Azure VM Agent
      ansible.builtin.package:
        name: waagent
        state: latest
      when: ansible_os_family in ['RedHat', 'Debian']

    - name: Configure Azure Monitor Agent
      ansible.builtin.include_role:
        name: vm_config
        tasks_from: monitor_agent

    - name: Register with Azure Recovery Services (real task)
      when: use_azure_collection | default(true)
      azure.azcollection.azure_rm_backup_protected_vm:
        resource_group: "{{ resource_group }}"
        vault_name: "{{ backup_vault }}"
        vm_name: "{{ inventory_hostname }}"
        policy_name: "DefaultPolicy"
        state: present

    - name: Register with Azure Recovery Services (fallback)
      when: not (use_azure_collection | default(true))
      ansible.builtin.debug:
        msg: |
          The azure.azcollection collection is not in use. To enable backup protection in a real run, install the collection listed in ansible/requirements.yml and run the playbook with use_azure_collection=true.
          Example CLI equivalent:
          az backup protection enable-for-vm --resource-group "{{ resource_group }}" --vault-name "{{ backup_vault }}" --vm "{{ inventory_hostname }}" --policy-name "DefaultPolicy"

    - name: Enable Security Center
      azure.azcollection.azure_rm_securitycenter:
        resource_group: "{{ resource_group }}"
        workspace: "{{ workspace_name }}"
        state: present

    - name: Ensure backup report directory exists
      ansible.builtin.file:
        path: "/tmp/migration_reports"
        state: directory
        mode: '0755'

    - name: Write migration note
      ansible.builtin.copy:
        dest: "/tmp/migration_reports/{{ inventory_hostname }}.txt"
        content: "Migration post-configuration completed for {{ inventory_hostname }}\n"