---
- name: Configure Post-Migration Setup
  hosts: azure_vms
  become: true

  vars:
    backup_vault: "{{ lookup('env', 'AZURE_BACKUP_VAULT') }}"
    resource_group: "{{ lookup('env', 'AZURE_RESOURCE_GROUP') }}"
    subscription_id: "{{ lookup('env', 'ARM_SUBSCRIPTION_ID') }}"

  tasks:
    - name: Install Azure VM Agent
      ansible.builtin.package:
        name: waagent
        state: present
      when: ansible_os_family in ['RedHat', 'Debian']

    - name: Configure Azure Monitor Agent
      ansible.builtin.include_role:
        name: vm_config
        tasks_from: monitor_agent

    - name: Check if Azure collection is available
      ansible.builtin.command: ansible-galaxy collection list azure.azcollection
      register: collection_check
      changed_when: false
      check_mode: false

    - name: Set collection availability fact
      ansible.builtin.set_fact:
        azure_collection_available: "{{ collection_check.rc == 0 }}"

    - name: Register with Azure Recovery Services
      # Using azure.azcollection.azure_rm_virtualmachine to enable backup protection
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ inventory_hostname }}"
        backup:
          vault_name: "{{ backup_vault }}"
          policy_name: "DefaultPolicy"
          enable: true
        state: present

    - name: Display backup protection info
      ansible.builtin.debug:
        msg: |
          Backup protection configured for VM {{ inventory_hostname }}:
          - Resource Group: {{ resource_group }}
          - Backup Vault: {{ backup_vault }}
          - Policy: DefaultPolicy

    - name: Configure Microsoft Defender for Cloud (Security Center)
      ansible.builtin.debug:
        msg: |
          To enable Microsoft Defender for Cloud (formerly Security Center):
          
          1. Enable auto-provisioning:
          az security auto-provisioning-setting update --name "default" --auto-provision "On"
          
          2. Enable Defender plans:
          az security pricing create -n "VirtualMachines" --tier "Standard"
          
          Resource Group: {{ resource_group }}
          VM: {{ inventory_hostname }}

    - name: Ensure backup report directory exists
      ansible.builtin.file:
        path: "/tmp/migration_reports"
        state: directory
        mode: '0755'

    - name: Write migration note
      ansible.builtin.copy:
        dest: "/tmp/migration_reports/{{ inventory_hostname }}.txt"
        content: "Migration post-configuration completed for {{ inventory_hostname }}\n"

