---
- name: Configure Post-Migration Setup
  hosts: azure_vms
  become: true

  vars:
    backup_vault: "{{ lookup('env', 'AZURE_BACKUP_VAULT') }}"
    resource_group: "{{ lookup('env', 'AZURE_RESOURCE_GROUP') }}"
    subscription_id: "{{ lookup('env', 'ARM_SUBSCRIPTION_ID') }}"

  tasks:
    - name: Install Azure VM Agent
      ansible.builtin.package:
        name: waagent
        state: latest
      when: ansible_os_family in ['RedHat', 'Debian']

    - name: Configure Azure Monitor Agent
      ansible.builtin.include_role:
        name: vm_config
        tasks_from: monitor_agent

    - name: Register with Azure Recovery Services
      azure.azcollection.azure_rm_recoveryservicesbackupprotecteditem:
        resource_group: "{{ resource_group }}"
        vault_name: "{{ backup_vault }}"
        item_name: "{{ inventory_hostname }}"
        backup_policy_id: "/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.RecoveryServices/vaults/{{ backup_vault }}/backupPolicies/vm-backup-policy"
        state: present

    - name: Enable Security Center
      azure.azcollection.azure_rm_securitycenter:
        resource_group: "{{ resource_group }}"
        workspace: "{{ workspace_name }}"
        state: present

    - name: Ensure backup report directory exists
      ansible.builtin.file:
        path: "/tmp/migration_reports"
        state: directory
        mode: '0755'

    - name: Write migration note
      ansible.builtin.copy:
        dest: "/tmp/migration_reports/{{ inventory_hostname }}.txt"
        content: "Migration post-configuration completed for {{ inventory_hostname }}\n"