------

- name: Configure Post-Migration Setup- name: Configure Post-Migration Setup

  hosts: azure_vms  hosts: azure_vms

  become: true  become: true

    

  vars:  vars:

    backup_vault: "{{ lookup('env', 'AZURE_BACKUP_VAULT') }}"    backup_vault: "{{ lookup('env', 'AZURE_BACKUP_VAULT') }}"

        

  tasks:  tasks:

    - name: Install Azure VM Agent    - name: Install Azure VM Agent

      package:      package:

        name: waagent        name: waagent

        state: latest        state: latest

      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

                

    - name: Configure Azure Monitor Agent    - name: Configure Azure Monitor Agent

      include_role:      include_role:

        name: vm_config        name: vm_config

        tasks_from: monitor_agent        tasks_from: monitor_agent

                

    - name: Register with Azure Recovery Services    - name: Register with Azure Backup

      azure.azcollection.azure_rm_recoveryservicesbackupprotecteditem:      azure.azcollection.azure_rm_backup_protected_vm:

        resource_group: "{{ resource_group }}"        resource_group: "{{ resource_group }}"

        vault_name: "{{ backup_vault }}"        vault_name: "{{ backup_vault }}"

        item_name: "{{ inventory_hostname }}"        vm_name: "{{ inventory_hostname }}"

        backup_policy_id: "/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.RecoveryServices/vaults/{{ backup_vault }}/backupPolicies/vm-backup-policy"        policy_name: "vm-backup-policy"

        state: present        state: present

                

    - name: Enable Security Center    - name: Enable Azure Defender

      azure.azcollection.azure_rm_securitycenter:      azure.azcollection.azure_rm_security_assessment:

        resource_group: "{{ resource_group }}"        resource_group: "{{ resource_group }}"

        workspace: "{{ workspace_name }}"        vm_name: "{{ inventory_hostname }}"

        state: present        name: "enable_endpoint_protection"
        state: present