name: Azure VM Migration Pipeline

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: 'VM to migrate'
        required: true
        type: string
      source_environment:
        description: 'Source environment'
        required: true
        type: choice
        options:
          - vmware
          - hyper-v
      target_environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - prod
          - staging
        default: 'prod'
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'ansible/**'
      - '.github/workflows/**'

env:
  # Mock environment variables for testing
  ARM_CLIENT_ID: "00000000-0000-0000-0000-000000000000"
  ARM_CLIENT_SECRET: "mock-client-secret"
  ARM_SUBSCRIPTION_ID: "00000000-0000-0000-0000-000000000000"
  ARM_TENANT_ID: "00000000-0000-0000-0000-000000000000"
  AZURE_MIGRATE_PROJECT: "mock-migrate-project"
  AZURE_RESOURCE_GROUP: "mock-resource-group"
  AZURE_BACKUP_VAULT: "mock-backup-vault"
  TF_IN_AUTOMATION: "true"
  ANSIBLE_COLLECTIONS_PATH: "~/.ansible/collections"

jobs:
  validate:
    name: Validate Configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.0.0"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Ansible and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==7.0.0
          pip install "ansible-lint>=6.22.2,<7.0.0"
          pip install "azure-cli-core>=2.40.0"
          
      - name: Install Ansible Collections
        run: |
          cd ansible
          ansible-galaxy collection install -r requirements.yml --force

      - name: Terraform Format
        run: |
          cd terraform
          terraform fmt -check -recursive

      - name: Run Ansible Lint
        run: |
          cd ansible
          ansible-galaxy collection install -r requirements.yml
          ansible-lint -v

  provision-infrastructure:
    needs: validate
    name: Provision Azure Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.0.0"
        
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
          
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -var-file=terraform.tfvars -out=tfplan
        
      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve tfplan